name: Build

on:
  push:
    branches: [ main ]

  # Allow manual triggering:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - uses: actions/checkout@v2
      - name: Build all apps
        run: make build
      - name: Push images
        run: make push
